# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.0.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        project_id: active-alchemy-459613-j5
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: github-actions@active-alchemy-459613-j5.iam.gserviceaccount.com

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Get existing GAR tags
      run: |
        TAGS=$(gcloud artifacts docker tags list \
          europe-west2-docker.pkg.dev/active-alchemy-459613-j5/nasa-app-europe-west-2/nasa-ui \
          --format="value(tag)" | grep "$(date +'%d-%m-%y')-v" || true)
    
        if [ -z "$TAGS" ]; then
          echo "ITERATION=1" >> $GITHUB_ENV
        else
          LAST=$(echo "$TAGS" | sed "s/.*-v//" | sort -n | tail -1)
          echo "ITERATION=$((LAST + 1))" >> $GITHUB_ENV
        fi


    - name: Create .env.production file from GitHub Secrets/Variables
      run: | 
          echo "REACT_APP_API_URL=${{vars.REACT_APP_API_URL}}" >> .env.production
    
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    - name: Build docker image
      run: docker build -t europe-west2-docker.pkg.dev/active-alchemy-459613-j5/nasa-app-europe-west-2/nasa-ui:$(date +'%d-%m-%y')-v${{ env.ITERATION }} .

    - name: Push to GAR
      run: docker push europe-west2-docker.pkg.dev/active-alchemy-459613-j5/nasa-app-europe-west-2/nasa-ui:$(date +'%d-%m-%y')-v${{ env.ITERATION }}
